### ISSUE TITLE
A concern about using exchange rate API (Limited numbers of uses)

### ISSUE THREAD

**Issue by yeonyeonn** [ez615/OSS_Final_Project#1]
I'm working on a currency exchange program using **'Free'** version of **Fixer Exchange rate API (https://fixer.io/product)** and it can only be used **100 times a month**. I already used up 100 times while writing the codes, so it can't be used anymore this month. 

There are some **possible solutions**. 
**1) Using another API**:  This is the most appropriate, but it will take a long time to write new codes. (I tried many other API, but they were hard to use.)

**2) Getting a new API key of Fixer API every time we use all 100 times**: Maybe the simplest way. (We need to receive a new API key when submitting this project on Icampus.)

**3) Using 'Basic' version of Fixer API by paying 10$ (https://fixer.io/product)**: Then it can be used 10000 times a month, but have to pay.

**Which one do you think is the best solution?**

현재 Fixer의 무료 버전 환율 API를 사용 중인데, 무료 버전 API는 한 달에 오직 100번만 사용할 수 있습니다. 이 사실을 간과하고 환전 프로그램을 짜던 중 100회를 모두 사용해버려 더 이상 이 API를 사용할 수 없게 되었습니다. 제가 고민해 본 가능한 해결책들은 다음과 같습니다. 

1) Fixer말고 다른 환율 API를 사용한다: 가장 적절한 방법이지만 새 코드를 짜는 데 걸릴 시간이 상당히 오래 걸릴 것으로 생각됩니다. 
(처음에 어떤 API를 쓸지 고민했던 과정에서 여러 API들을 시도해봤지만 기본적인 적용이 아주 어려웠습니다.  Fixer API 사용에 문제가 생긴 이후에도 이것저것 시도해보았으나 여전히 적용이 어려워 코드를 짜는 시간이 얼마 정도 걸릴 지 예측하기 어렵습니다.)

2) 100회를 다 사용할 때마다 새 API key를 발급받아 사용한다: 100회 제한이 있는 것은 API key당 해당하는 내용이기 때문에, 100회를 모두 사용할 때마다 Fixer에 새로 가입하고 key를 발급받는 식으로 사용할 수 있습니다. (만약 이 방법을 선택한다면 최종 프로젝트 제출 시 새 API key를 발급받아 제출하는 것이 안전할 것 같습니다.)

3) 10$를 지불하고 Fixer의 'Basic' 버전 API를 사용한다: 10달러를 내면 한 달에 10000번 사용 가능한 Fixer의 Basic 버전 API를 활용할 수 있습니다. 단지 금액을 지불해야 한다는 점이 우려됩니다. 

어떤 방법을 택하는 것이 가장 나을까요? 다른 좋은 아이디어가 있다면 편하게 말씀해주세요!!

**Comment by gbudjeakp** [comment]
I am not sure how often the API is called. is it click based, or on every page reload or both? If you're developing, then you're going to be calling that API a lot. Another question is, is this a SaaS product you are developing or is this just a personal project?  If it's a SaaS product you're making, get in touch with the API creators and see if you can get a pricing deal/plan with them. If it's a personal project and you do not want to spend any money then utilize another API. The code won't change much. It'll only be a small learning curve when trying out the new API.

**Comment by ez615** [comment]
If you're just using api to bring in the exchange rate, you'll have to think about how to set the cycle of using api. If the exchange rate changes too often when planning a trip, it may be difficult to budget. 
For example, there may be a way to make a country selection and use api only then. (Use Bootstrap > Forms > select)
While developing, it would be better to continue receiving new api and testing it.

api를 사용해서 그냥 환율만 불러오는거면 api를 사용하는 주기를 어떻게 정할지 생각해봐야 할 것 같습니다. 여행을 계획할때 환율이 너무 자주 바뀐다면 예산을 짜기 어려울 수도 있습니다.
 예를 들어 나라를 선택하는 부분을 만들어서 그때만 api를 사용한다는 방법이 있을 것 같습니다.(Bootstrap > Forms > select 사용)
개발하는 중에는 계속 새로 api를 받아 테스트 하는 것이 나을 것 같습니다.

**Comment by yeonyeonn** [comment]
> I am not sure how often the API is called. is it click based, or on every page reload or both? If you're developing, then you're going to be calling that API a lot. Another question is, is this a SaaS product you are developing or is this just a personal project? If it's a SaaS product you're making, get in touch with the API creators and see if you can get a pricing deal/plan with them. If it's a personal project and you do not want to spend any money then utilize another API. The code won't change much. It'll only be a small learning curve when trying out the new API.

Hi gbudjeakp, thank you for your advice! 
It's a personal project, so I am going to try out the new API as you told. :)

**Comment by yeonyeonn** [comment]
> If you're just using api to bring in the exchange rate, you'll have to think about how to set the cycle of using api. If the exchange rate changes too often when planning a trip, it may be difficult to budget. For example, there may be a way to make a country selection and use api only then. (Use Bootstrap > Forms > select) While developing, it would be better to continue receiving new api and testing it.
> 
> api를 사용해서 그냥 환율만 불러오는거면 api를 사용하는 주기를 어떻게 정할지 생각해봐야 할 것 같습니다. 여행을 계획할때 환율이 너무 자주 바뀐다면 예산을 짜기 어려울 수도 있습니다. 예를 들어 나라를 선택하는 부분을 만들어서 그때만 api를 사용한다는 방법이 있을 것 같습니다.(Bootstrap > Forms > select 사용) 개발하는 중에는 계속 새로 api를 받아 테스트 하는 것이 나을 것 같습니다.

좋은 아이디어 감사합니다!! 프로그램 내에서 api를 호출하는 주기를 최소화해야 하는 데 집중해야겠네요 ㅎㅎ
일단 오늘까지 다른 API를 시도해보고 불가능하면 기존 API에서 새로운 key를 부여받는 식으로 진행하겠습니다!
