### ISSUE TITLE
Total / Budget 구현 부분 의견 구합니다!

### ISSUE THREAD

**Issue by yeonyeonn** [ez615/OSS_Final_Project#2]
**환전 부분**을 구현하다 의문점이 생겨 문의드립니다! 지난 회의 때 논의되었던 내용이지만 제시해주신 아이디어를 제가 완전히 이해한 것이 맞는지 점검하고자 합니다. 

환전과 관련하여 저희가 구현하고 있는 내용은 '사용자가 **여행일자별로 하루하루 추가하는 Total, Budget 금액**을 **상단 박스**에 가져와 **최종적인 Total과 Budget 금액**을 **계산** 및 **환전**하기' 입니다. 

![image](https://user-images.githubusercontent.com/90249027/142739668-2abbe2cf-0a24-4e90-a341-6f5f1e34a8ee.png)

이때 
1) 사용자가 **일자별로 입력하는 Total, Budget** 및 **상단박스의 최종 Total과 Budget**은 **타 국가의 화폐** (ex. 달러화, 유료화)이며, 
2) 사용자는 **상단박스 우측에 select 기능**을 통해 **어떤 국가의 화폐**를 사용할 것인지 **선택**할 수 있습니다. 
3) 사용자는 **상단박스 우측의 노란 버튼**을 눌러 **타 국가 화폐단위**로 표현된 **최종 Total과 Budget**를 **한국 원화**로 환전한 금액을 확인할 수 있습니다. (원래 **타 국가 화폐**로 쓰여있던 텍스트가 **노란버튼** 누르면 **원화단위**로 바뀌어 표시됨. 다시 **노란버튼** 누르면 **타 국가 화폐 단위**로 표시됨)

제가 생각하는 내용은 위와 같은데, 혹시라도 잘못되거나 수정했으면 하는 부분이 있으시다면 말씀해주세요!

**Comment by ez615** [comment]
네네 제가 생각한 바랑 같습니다!
