### ISSUE TITLE
list box 크기 늘리기

### ISSUE THREAD

**Issue by yeonyeonn** [ez615/OSS_Final_Project#4]
안녕하세요!
현재 우리는 plan list 와 budget list를 작업 중에 있는데,
각 list에 항목을 추가할 때마다 박스 크기가 조정됩니다.
하지만 **추가되는 항목이 너무 많다면 list 박스의 크기가 지속적으로 커져 페이지 전체의 크기 또한 같이 늘어날 것 같습니다.**
따라서 list에 항목이 늘어나도 **크기를 고정**시킬 수 있는 기능을 추가하면 좋을 것 같습니다.
**list 박스를 고정시킬 수 있는 좋은 아이디어** 있을까요?

**Comment by ez615** [comment]
css에 overflow: auto를 사용해도 박스가 늘어나나요??

**Comment by yeonyeonn** [comment]
참고하여 해결했습니다! 감사합니다.
