### ISSUE TITLE
날짜를 재설정했을때 버그가 생깁니다.

### ISSUE THREAD

**Issue by ez615** [ez615/OSS_Final_Project#5]
처음에 날짜를 설정해서 main plan 부분이 복사된 후,
**새로고침을 하지 않고** 다시 **날짜를 재설정**했을 때 **clone된 부분이 없어지지 않고**
그 밑에 다시 새로운 container가 추가되는 현상이 일어나고 있습니다.
어떻게 하면 좋을지 조언 부탁드립니다.

**Comment by yeonyeonn** [comment]
1. clone된 div들을 담는 새로운 div를 만든다.
2. 이벤트 처리하는 함수 맨 처음에 날짜 첫설정인지 재설정인지 판별하는 조건문을 만든다.
3. 재설정이라면 clone을 감싸는 div 안을 비우고 다시 날짜에 따라 clone한다.
이런 순서로 하면 될 것 같습니다. 원래 clone 되어있던 div를 사용할 수 있으면 좋을 것 같은데, 그러면 조건문이 더 복잡해질 것 같습니다.
