### ISSUE TITLE
plan map area가 여러 개 생성되었을 때 budget list 추가 에러가 생깁니다!

### ISSUE THREAD

**Issue by yeonyeonn** [ez615/OSS_Final_Project#8]
main branch에 코드를 merge 시킨 후 api branch를 수정하고 있습니다.
여행 일자만큼 plan map area가 여러 개 생성되었을 때
새로 생성된 area들에 plan list는 정상적으로 잘 추가되는 반면
budget plan list는 추가가 되지 않습니다. 
(add시키는 함수조차 작동되지 않습니다.)
budget list는 api branch에서 따로 작업되어서 생긴 오류인 것 같은데,
혹시 clone된 area들에 plan을 add할 때 추가해야 하는 코드가 있을까요?

**Comment by ez615** [comment]
제가 방금 git pull 하여 확인해봤을때는 잘 작동하는 것 같은데, 지금 확인한 코드를 push해볼까요??

**Comment by ez615** [comment]
clone 함수가 하위 요소의 이벤트까지 클론하지 않아서 생기는 문제였습니다.
button.addEventListener를 없애고 버튼 클릭 이벤트를 onclick으로 수정하여 해결했으나
아직 plan list task가 첫번째 날에만 추가되는 버그가 남아있습니다. 확인해주세요!

**Comment by yeonyeonn** [comment]
task를 생성한 후 append 하는 위치 값을 조정하여 해결했습니다! 감사합니다.
